[package]
name = "lycaon"
version = "0.1.0"
authors = ["rmitsuboshi <rmitsuboshi.github@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grb        = "1.0.4"
rand       = "*"
serde      = { version = "1.0", features = ["rc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
