[package]
name = "miniboosts"
version = "0.2.3"
authors = ["rmitsuboshi <rmitsuboshi.github@gmail.com>"]
edition = "2021"

description = "MiniBoosts: A collection of boosting algorithms written in Rust 🦀"
repository  = "https://github.com/rmitsuboshi/miniboosts"
categories  = ["science"]
keywords    = ["boosting", "machine-learning"]

exclude = ["/tests", "/img", "TODO.txt"]
license = "MIT"


[dependencies]
grb        = { version = "1.3.0", optional = true }
rand       = { version = "0.8.5" }
rand_distr = { version = "0.4.3" }
rayon      = { version = "1.7.0" }
serde      = { version = "1.0.163", features = ["rc", "derive"] }
serde_json = { version = "1.0.96", default-features = false, features = ["alloc"] }
polars     = { version = "0.32.1" }

[features]
extended = ["grb"]
