[package]
name = "lycaon"
version = "0.1.0"
authors = ["rmitsuboshi <>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grb   = "1.0.4"
serde = { version = "1.0", features = ["derive"] }
