name: cargo build check
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build check on ${{ runner.name }}"
      - run: cargo build --release -F extended
  windows:
    runs-on: windows-latest
    steps:
      - run: echo "Build check on ${{ runner.name }}"
      - run: cargo build --release -F extended
  macos:
    runs-on: macos-latest
    steps:
      - run: echo "Build check on ${{ runner.name }}"
      - run: cargo build --release -F extended

